export { populatePlaceholder, clearPlaceholder } from "./placeholders.js"
export { default as enableRequiredFields } from "./enable-required-fields.js"
export { resetFormFields, resetCounter, resetForm } from "./form-reset.js"
export { showAltText, hideAltText } from "./alt-text.js"
export { updateCharacterCounter } from "./character-counter.js"
